CREATE TABLE IF NOT EXISTS teste (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS teste;

CREATE TABLE IF NOT EXISTS teste (
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (cpf)
);

--Modo errado:
INSERT INTO teste (cpf,nome,created_at)
VALUES ('33355599933','José Colméia','2021-07-30 17:00:00');

--Modo correto:
INSERT INTO teste (cpf,nome,created_at)
VALUES ('33355599933','José Colméia','2021-07-30 17:00:00') ON CONFLICT (cpf) DO NOTHING ;

UPDATE teste SET nome = 'João Silva' WHERE cpf = '33355599933';

SELECT nome FROM teste;