CREATE TABLE RODGLINS.DIM_VENDA_CLIENTE 
(
  SK_CLIENTE NUMBER(9, 0) NOT NULL 
, NK_CLIENTE NUMBER(9, 0) 
, NM_CLIENTE VARCHAR2(80 BYTE) 
, DT_NASCIMENTO DATE 
, DS_SEXO CHAR(1 BYTE) 
, NM_TIPO VARCHAR2(25 BYTE) 
, DS_TIPO VARCHAR2(60 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
, CONSTRAINT DIM_VENDA_CLIENTE_PK PRIMARY KEY 
  (
    SK_CLIENTE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.DIM_VENDA_CLIENTE_PK ON RODGLINS.DIM_VENDA_CLIENTE (SK_CLIENTE ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.DIM_VENDA_DATA 
(
  SK_DATA NUMBER(*, 0) NOT NULL 
, DATA DATE NOT NULL 
, ANO NUMBER(*, 0) NOT NULL 
, MES NUMBER(*, 0) NOT NULL 
, DIA NUMBER(*, 0) NOT NULL 
, DIA_SEMANA NUMBER(*, 0) NOT NULL 
, DIA_ANO NUMBER(*, 0) NOT NULL 
, ANO_BISSEXTO CHAR(1 BYTE) NOT NULL 
, DIA_UTIL CHAR(1 BYTE) NOT NULL 
, FIM_SEMANA CHAR(1 BYTE) NOT NULL 
, FERIADO CHAR(1 BYTE) NOT NULL 
, PRE_FERIADO CHAR(1 BYTE) NOT NULL 
, POS_FERIADO CHAR(1 BYTE) NOT NULL 
, NOME_FERIADO VARCHAR2(30 BYTE) 
, NOME_DIA_SEMANA VARCHAR2(15 BYTE) NOT NULL 
, NOME_DIA_SEMANA_ABREV CHAR(3 BYTE) NOT NULL 
, NOME_MES VARCHAR2(15 BYTE) NOT NULL 
, NOME_MES_ABREV CHAR(3 BYTE) NOT NULL 
, QUINZENA NUMBER(*, 0) NOT NULL 
, BIMESTRE NUMBER(*, 0) NOT NULL 
, TRIMESTRE NUMBER(*, 0) NOT NULL 
, SEMESTRE NUMBER(*, 0) NOT NULL 
, NR_SEMANA_MES NUMBER(*, 0) NOT NULL 
, NR_SEMANA_ANO NUMBER(*, 0) NOT NULL 
, ESTACAO_ANO VARCHAR2(15 BYTE) NOT NULL 
, DATA_POR_EXTENSO VARCHAR2(50 BYTE) NOT NULL 
, EVENTO VARCHAR2(50 BYTE) 
, CONSTRAINT SYS_C008934 PRIMARY KEY 
  (
    SK_DATA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C008934 ON RODGLINS.DIM_VENDA_DATA (SK_DATA ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.DIM_VENDA_DATA_C 
(
  SK_DATA NUMBER(*, 0) NOT NULL 
, DATA DATE NOT NULL 
, ANO NUMBER(*, 0) NOT NULL 
, MES NUMBER(*, 0) NOT NULL 
, DIA NUMBER(*, 0) NOT NULL 
, DIA_SEMANA NUMBER(*, 0) NOT NULL 
, DIA_ANO NUMBER(*, 0) NOT NULL 
, ANO_BISSEXTO CHAR(1 BYTE) NOT NULL 
, DIA_UTIL CHAR(1 BYTE) NOT NULL 
, FIM_SEMANA CHAR(1 BYTE) NOT NULL 
, FERIADO CHAR(1 BYTE) NOT NULL 
, PRE_FERIADO CHAR(1 BYTE) NOT NULL 
, POS_FERIADO CHAR(1 BYTE) NOT NULL 
, NOME_FERIADO VARCHAR2(30 BYTE) NOT NULL 
, NOME_DIA_SEMANA VARCHAR2(15 BYTE) NOT NULL 
, NOME_DIA_SEMANA_ABREV CHAR(3 BYTE) NOT NULL 
, NOME_MES VARCHAR2(15 BYTE) NOT NULL 
, NOME_MES_ABREV CHAR(3 BYTE) NOT NULL 
, QUINZENA NUMBER(*, 0) NOT NULL 
, BIMESTRE NUMBER(*, 0) NOT NULL 
, TRIMESTRE NUMBER(*, 0) NOT NULL 
, SEMESTRE NUMBER(*, 0) NOT NULL 
, NR_SEMANA_MES NUMBER(*, 0) NOT NULL 
, NR_SEMANA_ANO NUMBER(*, 0) NOT NULL 
, ESTACAO_ANO VARCHAR2(15 BYTE) NOT NULL 
, DATA_POR_EXTENSO VARCHAR2(50 BYTE) NOT NULL 
, EVENTO VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT SYS_C008972 PRIMARY KEY 
  (
    SK_DATA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C008972 ON RODGLINS.DIM_VENDA_DATA_C (SK_DATA ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.DIM_VENDA_LOJA 
(
  SK_LOJA NUMBER(9, 0) NOT NULL 
, NK_LOJA NUMBER(9, 0) 
, NM_LOJA VARCHAR2(25 BYTE) 
, DS_LOJA VARCHAR2(80 BYTE) 
, DS_ENDERECO VARCHAR2(120 BYTE) 
, NM_CIDADE VARCHAR2(80 BYTE) 
, SG_UF CHAR(2 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
, CONSTRAINT SYS_C008051 PRIMARY KEY 
  (
    SK_LOJA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C008051 ON RODGLINS.DIM_VENDA_LOJA (SK_LOJA ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.DIM_VENDA_PRODUTO 
(
  SK_PRODUTO NUMBER(9, 0) NOT NULL 
, NK_PRODUTO NUMBER(9, 0) 
, NM_PRODUTO VARCHAR2(20 BYTE) 
, DS_PRODUTO VARCHAR2(128 BYTE) 
, NM_MARCA VARCHAR2(60 BYTE) 
, NK_UNIDADE_MEDIDA NUMBER(2, 0) 
, DS_SIGLA CHAR(3 BYTE) 
, DS_UNIDADE_MEDIDA VARCHAR2(30 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
, CONSTRAINT SYS_C008052 PRIMARY KEY 
  (
    SK_PRODUTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C008052 ON RODGLINS.DIM_VENDA_PRODUTO (SK_PRODUTO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.DIM_VENDA_PROMOCAO 
(
  SK_PROMOCAO NUMBER(9, 0) NOT NULL 
, NK_PROMOCAO NUMBER(9, 0) 
, NM_PROMOCAO VARCHAR2(40 BYTE) 
, DS_PROMOCAO VARCHAR2(100 BYTE) 
, OBS_PROMOCAO VARCHAR2(100 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
, CONSTRAINT SYS_C008053 PRIMARY KEY 
  (
    SK_PROMOCAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C008053 ON RODGLINS.DIM_VENDA_PROMOCAO (SK_PROMOCAO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.DIM_VENDA_VENDEDOR 
(
  SK_VENDEDOR NUMBER(9, 0) NOT NULL 
, NK_VENDEDOR NUMBER(9, 0) 
, NM_VENDEDOR VARCHAR2(60 BYTE) 
, DT_NASCIMENTO DATE 
, DS_SEXO CHAR(9 BYTE) 
, DT_CONTRATACAO DATE 
, CD_FAIXA_BONIFICACAO NUMBER(2, 0) 
, DS_FAIXA_BONIFICACAO VARCHAR2(50 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
, CONSTRAINT SYS_C008337 PRIMARY KEY 
  (
    SK_VENDEDOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C008337 ON RODGLINS.DIM_VENDA_VENDEDOR (SK_VENDEDOR ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_ARQ_PROMOCOES 
(
  CD_PROMOCAO NUMBER(6, 0) NOT NULL 
, NM_PROMOCAO VARCHAR2(40 BYTE) 
, DS_PROMOCAO VARCHAR2(100 BYTE) 
, CONSTRAINT SYS_C007964 PRIMARY KEY 
  (
    CD_PROMOCAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C007964 ON RODGLINS.STG_ARQ_PROMOCOES (CD_PROMOCAO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_ARQ_PROMOCOES_OBS 
(
  CD_PROMOCAO_OBS NUMBER(6, 0) NOT NULL 
, CD_PROMOCAO NUMBER(6, 0) NOT NULL 
, OBS_NEGOCIO VARCHAR2(100 BYTE) 
, CONSTRAINT SYS_C007966 PRIMARY KEY 
  (
    CD_PROMOCAO_OBS 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.SYS_C007966 ON RODGLINS.STG_ARQ_PROMOCOES_OBS (CD_PROMOCAO_OBS ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_CLIENTE 
(
  SK_CLIENTE NUMBER(9, 0) NOT NULL 
, NK_CLIENTE NUMBER(9, 0) 
, NM_CLIENTE VARCHAR2(80 BYTE) 
, DT_NASCIMENTO DATE 
, DS_SEXO CHAR(1 BYTE) 
, NM_TIPO VARCHAR2(25 BYTE) 
, DS_TIPO VARCHAR2(60 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_FUNCIONARIO 
(
  SK_VENDEDOR NUMBER(9, 0) 
, NK_VENDEDOR NUMBER(9, 0) 
, NM_VENDEDOR VARCHAR2(60 BYTE) 
, DT_NASCIMENTO DATE 
, DS_SEXO CHAR(9 BYTE) 
, DT_CONTRATACAO DATE 
, CD_FAIXA_BONIFICACAO NUMBER(2, 0) 
, DS_FAIXA_BONIFICACAO VARCHAR2(50 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_LOJA 
(
  SK_LOJA NUMBER(9, 0) 
, NK_LOJA NUMBER(9, 0) 
, NM_LOJA VARCHAR2(25 BYTE) 
, DS_LOJA VARCHAR2(80 BYTE) 
, DS_ENDERECO VARCHAR2(120 BYTE) 
, NM_CIDADE VARCHAR2(80 BYTE) 
, SG_UF CHAR(2 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_PRODUTO 
(
  SK_PRODUTO NUMBER(9, 0) 
, NK_PRODUTO NUMBER(9, 0) 
, NM_PRODUTO VARCHAR2(20 BYTE) 
, DS_PRODUTO VARCHAR2(128 BYTE) 
, NM_MARCA VARCHAR2(60 BYTE) 
, NK_UNIDADE_MEDIDA NUMBER(2, 0) 
, DS_SIGLA CHAR(3 BYTE) 
, DS_UNIDADE_MEDIDA VARCHAR2(30 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_PROMOCOES 
(
  SK_PROMOCAO NUMBER(9, 0) 
, NK_PROMOCAO NUMBER(9, 0) 
, NM_PROMOCAO VARCHAR2(40 BYTE) 
, DS_PROMOCAO VARCHAR2(100 BYTE) 
, OBS_PROMOCAO VARCHAR2(100 BYTE) 
, DTC_INI DATE 
, DTC_FIM DATE 
, VERSION NUMBER(11, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_CIDADE 
(
  CD_CIDADE NUMBER(9, 0) NOT NULL 
, NM_CIDADE VARCHAR2(80 BYTE) 
, CD_UF NUMBER(2, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_CLASSIFICACAO_FISCAL 
(
  CD_CLASSIFICACAO_FISCAL NUMBER(4, 0) NOT NULL 
, NR_CFOP NUMBER(5, 0) NOT NULL 
, DS_NATUREZA_OPERACAO VARCHAR2(30 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_CLIENTE 
(
  CD_CLIENTE NUMBER(5, 0) NOT NULL 
, NM_CLIENTE VARCHAR2(60 BYTE) NOT NULL 
, DT_NASCIMENTO DATE 
, DS_SEXO CHAR(1 BYTE) NOT NULL 
, NR_CPF NUMBER(9, 0) NOT NULL 
, NR_CPF_DIG NUMBER(2, 0) NOT NULL 
, NR_RG NUMBER(9, 0) NOT NULL 
, NR_RG_DIG CHAR(1 BYTE) NOT NULL 
, DS_EMAIL VARCHAR2(80 BYTE) 
, CD_TIPO NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_ENDERECO 
(
  CD_ENDERECO NUMBER(9, 0) NOT NULL 
, NR_NUMERO NUMBER(6, 0) 
, NR_CEP VARCHAR2(10 BYTE) 
, NR_COMPLEMENTO VARCHAR2(20 BYTE) 
, CD_LOGRADOURO NUMBER(9, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_FUNCIONARIO 
(
  NR_MATRICULA NUMBER(5, 0) NOT NULL 
, CD_DEPTO NUMBER NOT NULL 
, NM_FUNCIONARIO VARCHAR2(60 BYTE) NOT NULL 
, DS_SEXO CHAR(1 BYTE) NOT NULL 
, DT_NASCIMENTO DATE 
, DT_ADMISSAO DATE NOT NULL 
, DS_ENDERECO VARCHAR2(80 BYTE) NOT NULL 
, VL_SALARIO NUMBER(7, 2) NOT NULL 
, CD_FAIXA_BONIFICACAO NUMBER(2, 0) NOT NULL 
, CD_LOJA NUMBER NOT NULL 
, T_SV_FUNCIONARIO_NR_MATRICULA NUMBER 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_ITEM_NOTA_FISCAL 
(
  NR_NOTA_FISCAL NUMBER(6, 0) NOT NULL 
, CD_ITEM NUMBER(3, 0) NOT NULL 
, CD_PRODUTO NUMBER(6, 0) NOT NULL 
, QT_VENDIDA NUMBER(3, 0) NOT NULL 
, VL_PRECO_UNITARIO NUMBER(6, 2) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_LOGRADOURO 
(
  CD_LOGRADOURO NUMBER(9, 0) NOT NULL 
, NM_LOGRADOURO VARCHAR2(60 BYTE) 
, CD_CIDADE NUMBER(9, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_LOJA 
(
  CD_LOJA NUMBER NOT NULL 
, NM_LOJA VARCHAR2(25 BYTE) 
, DS_LOJA VARCHAR2(60 BYTE) 
, CD_ENDERECO NUMBER(9, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_NOTA_FISCAL 
(
  NR_NOTA_FISCAL NUMBER(6, 0) NOT NULL 
, CD_CLASSIFICACAO_FISCAL NUMBER(4, 0) NOT NULL 
, CD_CLIENTE NUMBER(5, 0) NOT NULL 
, NR_MATRICULA NUMBER(5, 0) NOT NULL 
, DT_EMISSAO DATE NOT NULL 
, VL_TOTAL_NF NUMBER(8, 2) NOT NULL 
, DS_TIPO NUMBER(1, 0) NOT NULL 
, VL_DESCONTO NUMBER(3, 1) 
, CD_LOJA NUMBER NOT NULL 
, CD_PROMOCAO NUMBER(5, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_PRODUTO 
(
  CD_PRODUTO NUMBER(6, 0) NOT NULL 
, CD_UNIDADE_MEDIDA NUMBER NOT NULL 
, DS_PRODUTO VARCHAR2(20 BYTE) NOT NULL 
, DS_COMPLETA_PRODUTO VARCHAR2(128 BYTE) NOT NULL 
, VL_PRECO_UNITARIO NUMBER(6, 2) NOT NULL 
, DS_MARCA VARCHAR2(255 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_TIPO_CLIENTE 
(
  CD_TIPO NUMBER NOT NULL 
, NM_TIPO VARCHAR2(25 BYTE) 
, DS_TIPO VARCHAR2(60 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_UF 
(
  CD_UF NUMBER(2, 0) NOT NULL 
, SG_UF VARCHAR2(2 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_T_SV_UNIDADE_MEDIDA 
(
  CD_UNIDADE_MEDIDA NUMBER(2, 0) NOT NULL 
, DS_SIGLA CHAR(3 BYTE) NOT NULL 
, DS_UNIDADE_MEDIDA VARCHAR2(30 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.STG_VENDAS 
(
  SK_DATA NUMBER NOT NULL 
, DT_EMISSAO DATE 
, NK_CLIENTE NUMBER NOT NULL 
, NK_VENDEDOR NUMBER NOT NULL 
, NK_PROMOCAO NUMBER NOT NULL 
, NK_PRODUTO NUMBER NOT NULL 
, NK_LOJA NUMBER NOT NULL 
, DD_NOTA_FISCAL NUMBER(6, 0) NOT NULL 
, QTD_VENDIDA NUMBER(3, 0) 
, VL_PRECO_UNITARIO NUMBER(6, 2) 
, VL_TOTAL_PRECO NUMBER(9, 2) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_CLASSIFICACAO_FISCAL 
(
  CD_CLASSIFICACAO_FISCAL NUMBER(4, 0) NOT NULL 
, NR_CFOP NUMBER(5, 0) NOT NULL 
, DS_NATUREZA_OPERACAO VARCHAR2(30 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_TIPO_CLIENTE 
(
  CD_TIPO NUMBER NOT NULL 
, NM_TIPO VARCHAR2(25 BYTE) 
, DS_TIPO VARCHAR2(60 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_UF 
(
  CD_UF NUMBER(2, 0) NOT NULL 
, SG_UF VARCHAR2(2 BYTE) 
, CONSTRAINT T_SV_UF_PK PRIMARY KEY 
  (
    CD_UF 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.T_SV_UF_PK ON RODGLINS.T_SV_UF (CD_UF ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_UNIDADE_MEDIDA 
(
  CD_UNIDADE_MEDIDA NUMBER(2, 0) NOT NULL 
, DS_SIGLA CHAR(3 BYTE) NOT NULL 
, DS_UNIDADE_MEDIDA VARCHAR2(30 BYTE) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.FATO_VENDAS 
(
  SK_DATA NUMBER(9, 0) NOT NULL 
, SK_CLIENTE NUMBER(9, 0) NOT NULL 
, SK_VENDEDOR NUMBER(9, 0) NOT NULL 
, SK_PROMOCAO NUMBER(9, 0) NOT NULL 
, SK_PRODUTO NUMBER(9, 0) NOT NULL 
, SK_LOJA NUMBER(9, 0) NOT NULL 
, DD_NOTA_FISCAL NUMBER(6, 0) NOT NULL 
, QTD_VENDIDA NUMBER(3, 0) 
, VL_PRECO_UNITARIO NUMBER(6, 2) 
, VL_TOTAL_PRECO NUMBER(9, 2) 
, CONSTRAINT FATO_VENDAS_PK PRIMARY KEY 
  (
    SK_VENDEDOR 
  , SK_PRODUTO 
  , SK_PROMOCAO 
  , SK_DATA 
  , DD_NOTA_FISCAL 
  , SK_CLIENTE 
  , SK_LOJA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.FATO_VENDAS_PK ON RODGLINS.FATO_VENDAS (SK_VENDEDOR ASC, SK_PRODUTO ASC, SK_PROMOCAO ASC, SK_DATA ASC, DD_NOTA_FISCAL ASC, SK_CLIENTE ASC, SK_LOJA ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.FATO_VENDAS_C 
(
  SK_CLIENTE NUMBER(9, 0) NOT NULL 
, SK_VENDEDOR NUMBER(9, 0) NOT NULL 
, SK_PROMOCAO NUMBER(9, 0) NOT NULL 
, SK_PRODUTO NUMBER(9, 0) NOT NULL 
, SK_LOJA NUMBER(9, 0) NOT NULL 
, DD_NOTA_FISCAL NUMBER(6, 0) NOT NULL 
, QTD_VENDIDA NUMBER(3, 0) NOT NULL 
, VL_PRECO_UNITARIO NUMBER(6, 2) NOT NULL 
, VL_TOTAL_PRECO NUMBER(9, 2) NOT NULL 
, SK_DATA NUMBER(9, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_CLIENTE 
(
  CD_CLIENTE NUMBER(5, 0) NOT NULL 
, NM_CLIENTE VARCHAR2(60 BYTE) NOT NULL 
, DT_NASCIMENTO DATE 
, DS_SEXO CHAR(1 BYTE) NOT NULL 
, NR_CPF NUMBER(9, 0) NOT NULL 
, NR_CPF_DIG NUMBER(2, 0) NOT NULL 
, NR_RG NUMBER(9, 0) NOT NULL 
, NR_RG_DIG CHAR(1 BYTE) NOT NULL 
, DS_EMAIL VARCHAR2(80 BYTE) 
, CD_TIPO NUMBER NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_CIDADE 
(
  CD_CIDADE NUMBER(9, 0) NOT NULL 
, NM_CIDADE VARCHAR2(80 BYTE) 
, CD_UF NUMBER(2, 0) NOT NULL 
, CONSTRAINT T_SV_CIDADE_PK PRIMARY KEY 
  (
    CD_CIDADE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.T_SV_CIDADE_PK ON RODGLINS.T_SV_CIDADE (CD_CIDADE ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_PRODUTO 
(
  CD_PRODUTO NUMBER(6, 0) NOT NULL 
, CD_UNIDADE_MEDIDA NUMBER NOT NULL 
, DS_PRODUTO VARCHAR2(20 BYTE) NOT NULL 
, DS_COMPLETA_PRODUTO VARCHAR2(128 BYTE) NOT NULL 
, VL_PRECO_UNITARIO NUMBER(6, 2) NOT NULL 
, DS_MARCA VARCHAR2(255 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_LOGRADOURO 
(
  CD_LOGRADOURO NUMBER(9, 0) NOT NULL 
, NM_LOGRADOURO VARCHAR2(60 BYTE) 
, CD_CIDADE NUMBER(9, 0) NOT NULL 
, CONSTRAINT T_SV_LOGRADOURO_PK PRIMARY KEY 
  (
    CD_LOGRADOURO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.T_SV_LOGRADOURO_PK ON RODGLINS.T_SV_LOGRADOURO (CD_LOGRADOURO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_ENDERECO 
(
  CD_ENDERECO NUMBER(9, 0) NOT NULL 
, NR_NUMERO NUMBER(6, 0) 
, NR_CEP VARCHAR2(10 BYTE) 
, NR_COMPLEMENTO VARCHAR2(20 BYTE) 
, CD_LOGRADOURO NUMBER(9, 0) NOT NULL 
, CONSTRAINT T_SV_ENDERECO_PK PRIMARY KEY 
  (
    CD_ENDERECO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.T_SV_ENDERECO_PK ON RODGLINS.T_SV_ENDERECO (CD_ENDERECO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_LOJA 
(
  CD_LOJA NUMBER NOT NULL 
, NM_LOJA VARCHAR2(25 BYTE) 
, DS_LOJA VARCHAR2(60 BYTE) 
, CD_ENDERECO NUMBER(9, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_ESTOQUE 
(
  CD_LOJA NUMBER NOT NULL 
, CD_PRODUTO NUMBER(6, 0) NOT NULL 
, QT_ESTOQUE NUMBER(6, 0) 
, DT_ESTOQUE DATE 
, CONSTRAINT T_SV_ESTOQUE_PK PRIMARY KEY 
  (
    CD_LOJA 
  , CD_PRODUTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX RODGLINS.T_SV_ESTOQUE_PK ON RODGLINS.T_SV_ESTOQUE (CD_LOJA ASC, CD_PRODUTO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_FUNCIONARIO 
(
  NR_MATRICULA NUMBER(5, 0) NOT NULL 
, CD_DEPTO NUMBER NOT NULL 
, NM_FUNCIONARIO VARCHAR2(60 BYTE) NOT NULL 
, DS_SEXO CHAR(1 BYTE) NOT NULL 
, DT_NASCIMENTO DATE 
, DT_ADMISSAO DATE NOT NULL 
, DS_ENDERECO VARCHAR2(80 BYTE) NOT NULL 
, VL_SALARIO NUMBER(7, 2) NOT NULL 
, CD_FAIXA_BONIFICACAO NUMBER(2, 0) NOT NULL 
, CD_LOJA NUMBER NOT NULL 
, T_SV_FUNCIONARIO_NR_MATRICULA NUMBER 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_NOTA_FISCAL 
(
  NR_NOTA_FISCAL NUMBER(6, 0) NOT NULL 
, CD_CLASSIFICACAO_FISCAL NUMBER(4, 0) NOT NULL 
, CD_CLIENTE NUMBER(5, 0) NOT NULL 
, NR_MATRICULA NUMBER(5, 0) NOT NULL 
, DT_EMISSAO DATE NOT NULL 
, VL_TOTAL_NF NUMBER(8, 2) NOT NULL 
, DS_TIPO NUMBER(1, 0) NOT NULL 
, VL_DESCONTO NUMBER(3, 1) 
, CD_LOJA NUMBER NOT NULL 
, CD_PROMOCAO NUMBER(5, 0) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE TABLE RODGLINS.T_SV_ITEM_NOTA_FISCAL 
(
  NR_NOTA_FISCAL NUMBER(6, 0) NOT NULL 
, CD_ITEM NUMBER(3, 0) NOT NULL 
, CD_PRODUTO NUMBER(6, 0) NOT NULL 
, QT_VENDIDA NUMBER(3, 0) NOT NULL 
, VL_PRECO_UNITARIO NUMBER(6, 2) NOT NULL 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.CLASSIFICACAO_FISCAL_PK ON RODGLINS.T_SV_CLASSIFICACAO_FISCAL (CD_CLASSIFICACAO_FISCAL ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.NATUREZA_OPERACAO_UN ON RODGLINS.T_SV_CLASSIFICACAO_FISCAL (DS_NATUREZA_OPERACAO ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.T_SV_CLIENTE_PK ON RODGLINS.T_SV_CLIENTE (CD_CLIENTE ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.T_SV_FUNCIONARIO_PK ON RODGLINS.T_SV_FUNCIONARIO (NR_MATRICULA ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.T_SV_ITEM_NOTA_FISCAL_PK ON RODGLINS.T_SV_ITEM_NOTA_FISCAL (NR_NOTA_FISCAL ASC, CD_ITEM ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.T_SV_UN_PK ON RODGLINS.T_SV_LOJA (CD_LOJA ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.T_SV_NOTA_FISCAL_PK ON RODGLINS.T_SV_NOTA_FISCAL (NR_NOTA_FISCAL ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.DS_PRODUTO_UN ON RODGLINS.T_SV_PRODUTO (DS_PRODUTO ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.T_SV_PRODUTO_PK ON RODGLINS.T_SV_PRODUTO (CD_PRODUTO ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.T_SV_TIPO_CLIENTE_PK ON RODGLINS.T_SV_TIPO_CLIENTE (CD_TIPO ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.SV_DS_UNIDADE_MEDIDA_UN ON RODGLINS.T_SV_UNIDADE_MEDIDA (DS_UNIDADE_MEDIDA ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE UNIQUE INDEX RODGLINS.UNIDADE_MEDIDA_PK ON RODGLINS.T_SV_UNIDADE_MEDIDA (CD_UNIDADE_MEDIDA ASC) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE RODGLINS.T_SV_CLASSIFICACAO_FISCAL
ADD CONSTRAINT T_SV_CLASSIFICACAO_FISCAL_PK PRIMARY KEY 
(
  CD_CLASSIFICACAO_FISCAL 
)
USING INDEX CLASSIFICACAO_FISCAL_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_CLIENTE
ADD CONSTRAINT T_SV_CLIENTE_PK PRIMARY KEY 
(
  CD_CLIENTE 
)
USING INDEX T_SV_CLIENTE_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_FUNCIONARIO
ADD CONSTRAINT T_SV_FUNCIONARIO_PK PRIMARY KEY 
(
  NR_MATRICULA 
)
USING INDEX T_SV_FUNCIONARIO_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_ITEM_NOTA_FISCAL
ADD CONSTRAINT T_SV_ITEM_NOTA_FISCAL_PK PRIMARY KEY 
(
  NR_NOTA_FISCAL 
, CD_ITEM 
)
USING INDEX T_SV_ITEM_NOTA_FISCAL_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_LOJA
ADD CONSTRAINT T_SV_LOJA_PK PRIMARY KEY 
(
  CD_LOJA 
)
USING INDEX T_SV_UN_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_NOTA_FISCAL
ADD CONSTRAINT T_SV_NOTA_FISCAL_PK PRIMARY KEY 
(
  NR_NOTA_FISCAL 
)
USING INDEX T_SV_NOTA_FISCAL_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_PRODUTO
ADD CONSTRAINT T_SV_PRODUTO_PK PRIMARY KEY 
(
  CD_PRODUTO 
)
USING INDEX T_SV_PRODUTO_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_TIPO_CLIENTE
ADD CONSTRAINT T_SV_TIPO_CLIENTE_PK PRIMARY KEY 
(
  CD_TIPO 
)
USING INDEX T_SV_TIPO_CLIENTE_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_UNIDADE_MEDIDA
ADD CONSTRAINT T_SV_UNIDADE_MEDIDA_PK PRIMARY KEY 
(
  CD_UNIDADE_MEDIDA 
)
USING INDEX UNIDADE_MEDIDA_PK
ENABLE;

ALTER TABLE RODGLINS.T_SV_CLASSIFICACAO_FISCAL
ADD CONSTRAINT SV_DS_NATUREZA_OPERACAO_UN UNIQUE 
(
  DS_NATUREZA_OPERACAO 
)
USING INDEX NATUREZA_OPERACAO_UN
ENABLE;

ALTER TABLE RODGLINS.T_SV_PRODUTO
ADD CONSTRAINT T_SV_PRODUTO_DS_PRODUTO_UN UNIQUE 
(
  DS_PRODUTO 
)
USING INDEX DS_PRODUTO_UN
ENABLE;

ALTER TABLE RODGLINS.T_SV_UNIDADE_MEDIDA
ADD CONSTRAINT SV_DS_UNIDADE_MEDIDA_UN UNIQUE 
(
  DS_UNIDADE_MEDIDA 
)
USING INDEX SV_DS_UNIDADE_MEDIDA_UN
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS
ADD CONSTRAINT FAT_VENDAS_CLIENTE_FK FOREIGN KEY
(
  SK_CLIENTE 
)
REFERENCES RODGLINS.DIM_VENDA_CLIENTE
(
  SK_CLIENTE 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS
ADD CONSTRAINT FAT_VENDAS_DATA_FK_C FOREIGN KEY
(
  SK_DATA 
)
REFERENCES RODGLINS.DIM_VENDA_DATA_C
(
  SK_DATA 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS
ADD CONSTRAINT FAT_VENDAS_LOJA_FK FOREIGN KEY
(
  SK_LOJA 
)
REFERENCES RODGLINS.DIM_VENDA_LOJA
(
  SK_LOJA 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS
ADD CONSTRAINT FAT_VENDAS_PRODUTO_FK FOREIGN KEY
(
  SK_PRODUTO 
)
REFERENCES RODGLINS.DIM_VENDA_PRODUTO
(
  SK_PRODUTO 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS
ADD CONSTRAINT FAT_VENDAS_PROMOCAO_FK FOREIGN KEY
(
  SK_PROMOCAO 
)
REFERENCES RODGLINS.DIM_VENDA_PROMOCAO
(
  SK_PROMOCAO 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS
ADD CONSTRAINT FAT_VENDAS_VENDEDOR_FK FOREIGN KEY
(
  SK_VENDEDOR 
)
REFERENCES RODGLINS.DIM_VENDA_VENDEDOR
(
  SK_VENDEDOR 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS_C
ADD CONSTRAINT FAT_VENDAS_CLIENTE_FK_C FOREIGN KEY
(
  SK_CLIENTE 
)
REFERENCES RODGLINS.DIM_VENDA_CLIENTE
(
  SK_CLIENTE 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS_C
ADD CONSTRAINT FAT_VENDAS_LOJA_FK_C FOREIGN KEY
(
  SK_LOJA 
)
REFERENCES RODGLINS.DIM_VENDA_LOJA
(
  SK_LOJA 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS_C
ADD CONSTRAINT FAT_VENDAS_PRODUTO_FK_C FOREIGN KEY
(
  SK_PRODUTO 
)
REFERENCES RODGLINS.DIM_VENDA_PRODUTO
(
  SK_PRODUTO 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS_C
ADD CONSTRAINT FAT_VENDAS_PROMOCAO_FK_C FOREIGN KEY
(
  SK_PROMOCAO 
)
REFERENCES RODGLINS.DIM_VENDA_PROMOCAO
(
  SK_PROMOCAO 
)
ENABLE;

ALTER TABLE RODGLINS.FATO_VENDAS_C
ADD CONSTRAINT FAT_VENDAS_VENDEDOR_FK_C FOREIGN KEY
(
  SK_VENDEDOR 
)
REFERENCES RODGLINS.DIM_VENDA_VENDEDOR
(
  SK_VENDEDOR 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_CIDADE
ADD CONSTRAINT T_SV_CIDADE_T_SV_UF_FK FOREIGN KEY
(
  CD_UF 
)
REFERENCES RODGLINS.T_SV_UF
(
  CD_UF 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_CLIENTE
ADD CONSTRAINT T_SV_TIPO_CLIENTE_FK FOREIGN KEY
(
  CD_TIPO 
)
REFERENCES RODGLINS.T_SV_TIPO_CLIENTE
(
  CD_TIPO 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_ENDERECO
ADD CONSTRAINT T_SV_LOGRADOURO_FK FOREIGN KEY
(
  CD_LOGRADOURO 
)
REFERENCES RODGLINS.T_SV_LOGRADOURO
(
  CD_LOGRADOURO 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_ESTOQUE
ADD CONSTRAINT T_SV_ESTOQUE_T_SV_LOJA_FK FOREIGN KEY
(
  CD_LOJA 
)
REFERENCES RODGLINS.T_SV_LOJA
(
  CD_LOJA 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_ESTOQUE
ADD CONSTRAINT T_SV_ESTOQUE_T_SV_PRODUTO_FK FOREIGN KEY
(
  CD_PRODUTO 
)
REFERENCES RODGLINS.T_SV_PRODUTO
(
  CD_PRODUTO 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_FUNCIONARIO
ADD CONSTRAINT T_SV_LOJA_FK FOREIGN KEY
(
  CD_LOJA 
)
REFERENCES RODGLINS.T_SV_LOJA
(
  CD_LOJA 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_ITEM_NOTA_FISCAL
ADD CONSTRAINT T_SV_NOTA_FISCAL_FK FOREIGN KEY
(
  NR_NOTA_FISCAL 
)
REFERENCES RODGLINS.T_SV_NOTA_FISCAL
(
  NR_NOTA_FISCAL 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_ITEM_NOTA_FISCAL
ADD CONSTRAINT T_SV_PRODUTO_FK FOREIGN KEY
(
  CD_PRODUTO 
)
REFERENCES RODGLINS.T_SV_PRODUTO
(
  CD_PRODUTO 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_LOGRADOURO
ADD CONSTRAINT T_SV_CIDADE_FK FOREIGN KEY
(
  CD_CIDADE 
)
REFERENCES RODGLINS.T_SV_CIDADE
(
  CD_CIDADE 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_LOJA
ADD CONSTRAINT T_SV_LOJA_T_SV_ENDERECO_FK FOREIGN KEY
(
  CD_ENDERECO 
)
REFERENCES RODGLINS.T_SV_ENDERECO
(
  CD_ENDERECO 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_NOTA_FISCAL
ADD CONSTRAINT T_SV_CLASSIFICACAO_FISCAL_FK FOREIGN KEY
(
  CD_CLASSIFICACAO_FISCAL 
)
REFERENCES RODGLINS.T_SV_CLASSIFICACAO_FISCAL
(
  CD_CLASSIFICACAO_FISCAL 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_NOTA_FISCAL
ADD CONSTRAINT T_SV_CLIENTE_FK FOREIGN KEY
(
  CD_CLIENTE 
)
REFERENCES RODGLINS.T_SV_CLIENTE
(
  CD_CLIENTE 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_NOTA_FISCAL
ADD CONSTRAINT T_SV_FUNCIONARIO_FK FOREIGN KEY
(
  NR_MATRICULA 
)
REFERENCES RODGLINS.T_SV_FUNCIONARIO
(
  NR_MATRICULA 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_NOTA_FISCAL
ADD CONSTRAINT T_SV_NF_LOJA_FK FOREIGN KEY
(
  CD_LOJA 
)
REFERENCES RODGLINS.T_SV_LOJA
(
  CD_LOJA 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_PRODUTO
ADD CONSTRAINT T_SV_UNIDADE_MEDIDA_FK FOREIGN KEY
(
  CD_UNIDADE_MEDIDA 
)
REFERENCES RODGLINS.T_SV_UNIDADE_MEDIDA
(
  CD_UNIDADE_MEDIDA 
)
ENABLE;

ALTER TABLE RODGLINS.T_SV_CLIENTE
ADD CONSTRAINT CK_SV_CLIENTE_SEXO CHECK 
(UPPER(DS_SEXO) = 'F'
    OR
        UPPER(DS_SEXO) = 'M')
ENABLE;

ALTER TABLE RODGLINS.T_SV_FUNCIONARIO
ADD CONSTRAINT CK_SV_SALARIO_MIN CHECK 
(VL_SALARIO >= 880)
ENABLE;

ALTER TABLE RODGLINS.T_SV_ITEM_NOTA_FISCAL
ADD CONSTRAINT CK_SV_ITEM_NF_QTDEVEND CHECK 
(QT_VENDIDA > 0)
ENABLE;

ALTER TABLE RODGLINS.T_SV_NOTA_FISCAL
ADD CONSTRAINT CK_SV_NF_DESCONTO CHECK 
(VL_DESCONTO >= 0
    AND
        VL_DESCONTO <= 25)
ENABLE;

ALTER TABLE RODGLINS.T_SV_NOTA_FISCAL
ADD CONSTRAINT CK_SV_NF_TIPO CHECK 
(DS_TIPO IN (
        1,2
    ))
ENABLE;

ALTER TABLE RODGLINS.T_SV_PRODUTO
ADD CONSTRAINT CK_SV_PROD_PRECO CHECK 
(VL_PRECO_UNITARIO > 0)
ENABLE;
