REM INSERTING into SYS.AQ$_QUEUE_TABLE_AFFINITIES
SET DEFINE OFF;
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('19494','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('19521','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('19555','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('19613','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('19871','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('20088','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('20114','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('20126','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('20447','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('20610','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('20754','0','0','1');
Insert into SYS.AQ$_QUEUE_TABLE_AFFINITIES (TABLE_OBJNO,PRIMARY_INSTANCE,SECONDARY_INSTANCE,OWNER_INSTANCE) values ('22467','0','0','1');
