REM INSERTING into SYS.CDB_TS$
SET DEFINE OFF;
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('0','SYSTEM','2','1','0','1427604','1','2','0',null,null,null,null,null);
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('1','SYSAUX','2','1','0','1427607','1','2','0',null,null,null,null,null);
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('2','UNDOTBS1','2','1','0','1427609','1','2','0',null,null,null,null,null);
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('3','TEMP','2','1','0','1427611','1','0','0',null,null,null,null,null);
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('0','SYSTEM','3','1','0','1456267','1','2','1',null,null,null,null,null);
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('1','SYSAUX','3','1','0','1456270','1','2','1',null,null,null,null,null);
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('2','UNDOTBS1','3','1','0','1456272','1','2','1',null,null,null,null,null);
Insert into SYS.CDB_TS$ (TS#,NAME,CON_ID#,STATUS$,CSCNWRP,CSCNBAS,FILECNT,FLAGS,PTYPE,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5) values ('3','TEMP','3','1','0','1456274','1','0','1',null,null,null,null,null);
