REM INSERTING into SYS.DIMLEVEL$
SET DEFINE OFF;
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73648','1','CHANNEL_TOTAL',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73648','2','CHANNEL_CLASS',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73648','3','CHANNEL',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73649','1','CATEGORY',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73649','2','PROMO',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73649','3','PROMO_TOTAL',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73649','4','SUBCATEGORY',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','1','QUARTER',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','2','DAY',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','3','MONTH',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','4','FIS_YEAR',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','5','YEAR',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','6','FIS_QUARTER',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','7','FIS_WEEK',null,null,null,null,'0');
Insert into SYS.DIMLEVEL$ (DIMOBJ#,LEVELID#,LEVELNAME,SPARE1,SPARE2,SPARE3,SPARE4,FLAGS) values ('73650','8','FIS_MONTH',null,null,null,null,'0');
