REM INSERTING into SYS.FED$EDITIONS
SET DEFINE OFF;
Insert into SYS.FED$EDITIONS (APPID#,VER#,PATCH#,EDITION_NAME,EDITION_SEQ,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values ('2','0','0','ORA$BASE','0',null,null,null,null,null,null);
Insert into SYS.FED$EDITIONS (APPID#,VER#,PATCH#,EDITION_NAME,EDITION_SEQ,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values ('2','1','0','ORA$BASE','0',null,null,null,null,null,null);
