REM INSERTING into SYS.FED$VERSIONS
SET DEFINE OFF;
Insert into SYS.FED$VERSIONS (APPID#,VER#,TGTVER,ROOT_CLONE_CON_UID#,CMNT,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values ('2','1','1.0','0',null,null,null,null,null,null,null);
