REM INSERTING into SYS.FED$APPS
SET DEFINE OFF;
Insert into SYS.FED$APPS (APP_NAME,APPID#,VER#,APP_STATUS,FLAG,SRVN,MODN,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values ('APP$CDB$SYSTEM','2','1','0','144','SYS$USERS','catcon(pid=356)','0',null,null,null,null,null);
Insert into SYS.FED$APPS (APP_NAME,APPID#,VER#,APP_STATUS,FLAG,SRVN,MODN,SPARE1,SPARE2,SPARE3,SPARE4,SPARE5,SPARE6) values ('_CURRENT_STATE','1','0','0','0',null,null,'0',null,null,null,null,null);
