--------------------------------------------------------
--  File created - Monday-October-11-2021   
--------------------------------------------------------
@C:\Users\rodgl\ACCESS__DATA_TABLE.sql
@C:\Users\rodgl\ACLMV__DATA_TABLE.sql
@C:\Users\rodgl\ACLMV__REFLOG_DATA_TABLE.sql
@C:\Users\rodgl\ACLMVREFSTAT__DATA_TABLE.sql
@C:\Users\rodgl\ACLMVSUBTBL__DATA_TABLE.sql
@C:\Users\rodgl\ADMINAUTH__DATA_TABLE.sql
@C:\Users\rodgl\ADO_IMPARAM__DATA_TABLE.sql
@C:\Users\rodgl\ADO_IMSEGSTAT__DATA_TABLE.sql
@C:\Users\rodgl\ADO_IMSEGTASKDETAILS__DATA_TABLE.sql
@C:\Users\rodgl\ADO_IMSTAT__DATA_TABLE.sql
@C:\Users\rodgl\ADO_IMTASKS__DATA_TABLE.sql
@C:\Users\rodgl\ALL_UNIFIED_AUDIT_ACTIONS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__AUTO_CDR_COLUMN_GROUPS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__BATCH_SQL_STATS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__CDR_INFO_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__CHANGE_HANDLERS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__CONF_HDLR_COLUMNS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__CONSTRAINT_COLUMNS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__COORDINATOR_STATS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__DEST_OBJ_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__DEST_OBJ_CMAP_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__DEST_OBJ_OPS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__ERROR_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__ERROR_HANDLER_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__ERROR_TXN_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__PROCEDURE_STATS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__READER_STATS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__SERVER_STATS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__SOURCE_OBJ_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__SOURCE_SCHEMA_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__TABLE_STATS_DATA_TABLE.sql
@C:\Users\rodgl\APPLY__VIRTUAL_OBJ_CONS_DATA_TABLE.sql
@C:\Users\rodgl\APPROLE__DATA_TABLE.sql
@C:\Users\rodgl\AQ__DEQUEUE_LOG_PARTITION_MAP_DATA_TABLE.sql
@C:\Users\rodgl\AQ__DURABLE_SUBS_DATA_TABLE.sql
@C:\Users\rodgl\AQ__E_QUEUE_PARTITION_MAP_DATA_TABLE.sql
@C:\Users\rodgl\AQ__MESSAGE_TYPES_DATA_TABLE.sql
@C:\Users\rodgl\AQ__PENDING_MESSAGES_DATA_TABLE.sql
@C:\Users\rodgl\AQ__PROPAGATION_STATUS_DATA_TABLE.sql
@C:\Users\rodgl\AQ__PUBLISHER_DATA_TABLE.sql
@C:\Users\rodgl\AQ__QUEUE_PARAMS_DATA_TABLE.sql
@C:\Users\rodgl\AQ__QUEUE_PARTITION_MAP_DATA_TABLE.sql
@C:\Users\rodgl\AQ__QUEUE_SHARDS_DATA_TABLE.sql
@C:\Users\rodgl\AQ__QUEUE_STATISTICS_DATA_TABLE.sql
@C:\Users\rodgl\AQ__QUEUE_TABLE_AFFINITIES_DATA_TABLE.sql
@C:\Users\rodgl\AQ__REPLAY_INFO_DATA_TABLE.sql
@C:\Users\rodgl\AQ__SCHEDULES_DATA_TABLE.sql
@C:\Users\rodgl\AQ__SHARD_MAP_DATA_TABLE.sql
@C:\Users\rodgl\AQ__SUBSCRIBER_LWM_DATA_TABLE.sql
@C:\Users\rodgl\AQ__SUBSCRIBER_TABLE_DATA_TABLE.sql
@C:\Users\rodgl\ARGUMENT__DATA_TABLE.sql
@C:\Users\rodgl\ASSEMBLY__DATA_TABLE.sql
@C:\Users\rodgl\ASSOCIATION__DATA_TABLE.sql
@C:\Users\rodgl\ATEMPTAB__DATA_TABLE.sql
@C:\Users\rodgl\ATTRCOL__DATA_TABLE.sql
@C:\Users\rodgl\ATTRIBUTE__DATA_TABLE.sql
@C:\Users\rodgl\ATTRIBUTE_TRANSFORMATIONS__DATA_TABLE.sql
@C:\Users\rodgl\AUD__DATA_TABLE.sql
@C:\Users\rodgl\AUD_CONTEXT__DATA_TABLE.sql
@C:\Users\rodgl\AUDIT__DATA_TABLE.sql
@C:\Users\rodgl\AUDIT_ACTIONS_DATA_TABLE.sql
@C:\Users\rodgl\AUDIT_NG__DATA_TABLE.sql
@C:\Users\rodgl\AUD_OBJECT_OPT__DATA_TABLE.sql
@C:\Users\rodgl\AUD_POLICY__DATA_TABLE.sql
@C:\Users\rodgl\AUDTAB_TBS_FOR_EXPORT_TBL_DATA_TABLE.sql
@C:\Users\rodgl\AUX_STATS__DATA_TABLE.sql
@C:\Users\rodgl\AV_DUAL_DATA_TABLE.sql
@C:\Users\rodgl\AW__DATA_TABLE.sql
@C:\Users\rodgl\AW_AWCREATE_DATA_TABLE.sql
@C:\Users\rodgl\AW_AWCREATE10G_DATA_TABLE.sql
@C:\Users\rodgl\AW_AWMD_DATA_TABLE.sql
@C:\Users\rodgl\AW_AWREPORT_DATA_TABLE.sql
@C:\Users\rodgl\AW_AWXML_DATA_TABLE.sql
@C:\Users\rodgl\AW_EXPRESS_DATA_TABLE.sql
@C:\Users\rodgl\AW_OBJ__DATA_TABLE.sql
@C:\Users\rodgl\AW_PRG__DATA_TABLE.sql
@C:\Users\rodgl\AW_PROP__DATA_TABLE.sql
@C:\Users\rodgl\AW_TRACK__DATA_TABLE.sql
@C:\Users\rodgl\BOOTSTRAP__DATA_TABLE.sql
@C:\Users\rodgl\CACHE_STATS_0__DATA_TABLE.sql
@C:\Users\rodgl\CACHE_STATS_1__DATA_TABLE.sql
@C:\Users\rodgl\CAPTURED_PRIV__DATA_TABLE.sql
@C:\Users\rodgl\CAPTURE_RUN_LOG__DATA_TABLE.sql
@C:\Users\rodgl\CCOL__DATA_TABLE.sql
@C:\Users\rodgl\CDB_FILE__DATA_TABLE.sql
@C:\Users\rodgl\CDB_LOCAL_ADMINAUTH__DATA_TABLE.sql
@C:\Users\rodgl\CDB_PROPS__DATA_TABLE.sql
@C:\Users\rodgl\CDB_RESOURCE_PLAN__DATA_TABLE.sql
@C:\Users\rodgl\CDB_RESOURCE_PLAN_DIRECTIVE__DATA_TABLE.sql
@C:\Users\rodgl\CDB_SERVICE__DATA_TABLE.sql
@C:\Users\rodgl\CDB_TS__DATA_TABLE.sql
@C:\Users\rodgl\CDBVW_STATS__DATA_TABLE.sql
@C:\Users\rodgl\CDEF__DATA_TABLE.sql
@C:\Users\rodgl\CHANNELS_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__CLAUSE_DEPENDENTS_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__CLAUSES_DATA_TABLE.sql
@C:\Users\rodgl\CHNFDIRECTLOAD__DATA_TABLE.sql
@C:\Users\rodgl\CHNF__GROUP_FILTER_IOT_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__QUERIES_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__QUERY_BINDS_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__QUERY_DELTAS_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__QUERY_DEPENDENCIES_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__QUERY_OBJECT_DATA_TABLE.sql
@C:\Users\rodgl\CHNF__REG_QUERIES_DATA_TABLE.sql
@C:\Users\rodgl\CLI_INST__DATA_TABLE.sql
@C:\Users\rodgl\CLI_LOG__DATA_TABLE.sql
@C:\Users\rodgl\CLI_PART__DATA_TABLE.sql
@C:\Users\rodgl\CLI_TAB__DATA_TABLE.sql
@C:\Users\rodgl\CLI_TS__DATA_TABLE.sql
@C:\Users\rodgl\CLST__DATA_TABLE.sql
@C:\Users\rodgl\CLSTDIMENSION__DATA_TABLE.sql
@C:\Users\rodgl\CLSTJOIN__DATA_TABLE.sql
@C:\Users\rodgl\CLSTKEY__DATA_TABLE.sql
@C:\Users\rodgl\CLU__DATA_TABLE.sql
@C:\Users\rodgl\CLUSTER_DATABASES_DATA_TABLE.sql
@C:\Users\rodgl\CLUSTER_INSTANCES_DATA_TABLE.sql
@C:\Users\rodgl\CLUSTER_NODES_DATA_TABLE.sql
@C:\Users\rodgl\CODEAUTH__DATA_TABLE.sql
@C:\Users\rodgl\COL__DATA_TABLE.sql
@C:\Users\rodgl\COL_GROUP_USAGE__DATA_TABLE.sql
@C:\Users\rodgl\COLLECTION__DATA_TABLE.sql
@C:\Users\rodgl\COLTYPE__DATA_TABLE.sql
@C:\Users\rodgl\COLUMN_STAT__DATA_TABLE.sql
@C:\Users\rodgl\COL_USAGE__DATA_TABLE.sql
@C:\Users\rodgl\COM__DATA_TABLE.sql
@C:\Users\rodgl\COMPARISON__DATA_TABLE.sql
@C:\Users\rodgl\COMPARISON_COL__DATA_TABLE.sql
@C:\Users\rodgl\COMPARISON_ROW_DIF__DATA_TABLE.sql
@C:\Users\rodgl\COMPARISON_SCAN__DATA_TABLE.sql
@C:\Users\rodgl\COMPARISON_SCAN_VAL__DATA_TABLE.sql
@C:\Users\rodgl\COMPRESSION__DATA_TABLE.sql
@C:\Users\rodgl\COMPRESSION_STAT__DATA_TABLE.sql
@C:\Users\rodgl\CON__DATA_TABLE.sql
@C:\Users\rodgl\CONDATA__DATA_TABLE.sql
@C:\Users\rodgl\CONNECTION_TESTS__DATA_TABLE.sql
@C:\Users\rodgl\CONTAINER__DATA_TABLE.sql
@C:\Users\rodgl\CONTEXT__DATA_TABLE.sql
@C:\Users\rodgl\COUNTRIES_DATA_TABLE.sql
@C:\Users\rodgl\CPOOL__DATA_TABLE.sql
@C:\Users\rodgl\CRC__RESULT_CACHE_STATS_DATA_TABLE.sql
@C:\Users\rodgl\CUSTOMERS_DATA_TABLE.sql
@C:\Users\rodgl\DAM_CLEANUP_EVENTS__DATA_TABLE.sql
@C:\Users\rodgl\DAM_CLEANUP_JOBS__DATA_TABLE.sql
@C:\Users\rodgl\DAM_CONFIG_PARAM__DATA_TABLE.sql
@C:\Users\rodgl\DAM_LAST_ARCH_TS__DATA_TABLE.sql
@C:\Users\rodgl\DAM_PARAM_TAB__DATA_TABLE.sql
@C:\Users\rodgl\DATA_PUMP_XPL_TABLE__DATA_TABLE.sql
@C:\Users\rodgl\DBA_SENSITIVE_DATA_TBL_DATA_TABLE.sql
@C:\Users\rodgl\DBA_TSDP_POLICY_PROTECTION_TBL_DATA_TABLE.sql
@C:\Users\rodgl\DBFS__CLIENTS_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__BACKUPFILETABLE_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__CONTENTFNMAPTBL_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__FS_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__PROPERTY_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__SFLOCATORTABLE_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__STORECOMMANDS_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__STOREIDTABLE_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__STOREID2POLICYCTX_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_HS__STOREPROPERTIES_DATA_TABLE.sql
@C:\Users\rodgl\DBFS__MOUNTS_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_SFS__FS_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_SFS__FST_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_SFS__FSTO_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_SFS__FSTP_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_SFS__SNAP_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_SFS__TAB_DATA_TABLE.sql
@C:\Users\rodgl\DBFS_SFS__VOL_DATA_TABLE.sql
@C:\Users\rodgl\DBFS__STATS_DATA_TABLE.sql
@C:\Users\rodgl\DBFS__STORES_DATA_TABLE.sql
@C:\Users\rodgl\DBMS_ALERT_INFO_DATA_TABLE.sql
@C:\Users\rodgl\DBMS_LOCK_ALLOCATED_DATA_TABLE.sql
@C:\Users\rodgl\DBMS_PARALLEL_EXECUTE_CHUNKS__DATA_TABLE.sql
@C:\Users\rodgl\DBMS_PARALLEL_EXECUTE_TASK__DATA_TABLE.sql
@C:\Users\rodgl\DBMS_SQLPATCH_FILES_DATA_TABLE.sql
@C:\Users\rodgl\DBMS_SQLPATCH_STATE_DATA_TABLE.sql
@C:\Users\rodgl\DBMS_STATS_ID_MAP_TAB_DATA_TABLE.sql
@C:\Users\rodgl\DBMS_STATS_OBJ_LIST_TAB_DATA_TABLE.sql
@C:\Users\rodgl\DDL_REQUESTS_DATA_TABLE.sql
@C:\Users\rodgl\DDL_REQUESTS_PWD_DATA_TABLE.sql
@C:\Users\rodgl\DEFAULT_PWD__DATA_TABLE.sql
@C:\Users\rodgl\DEFERRED_STG__DATA_TABLE.sql
@C:\Users\rodgl\DEFROLE__DATA_TABLE.sql
@C:\Users\rodgl\DEFSUBPART__DATA_TABLE.sql
@C:\Users\rodgl\DEFSUBPARTLOB__DATA_TABLE.sql
@C:\Users\rodgl\DEPARTMENTS_DATA_TABLE.sql
@C:\Users\rodgl\DEPENDENCY__DATA_TABLE.sql
@C:\Users\rodgl\DIANA_VERSION__DATA_TABLE.sql
@C:\Users\rodgl\DIM__DATA_TABLE.sql
@C:\Users\rodgl\DIMATTR__DATA_TABLE.sql
@C:\Users\rodgl\DIMENSION_EXCEPTIONS_DATA_TABLE.sql
@C:\Users\rodgl\DIMJOINKEY__DATA_TABLE.sql
@C:\Users\rodgl\DIMLEVEL__DATA_TABLE.sql
@C:\Users\rodgl\DIMLEVELKEY__DATA_TABLE.sql
@C:\Users\rodgl\DIR__DATA_TABLE.sql
@C:\Users\rodgl\DIR_ALERT_HISTORY_DATA_TABLE.sql
@C:\Users\rodgl\DIR_DATABASE_ATTRIBUTES_DATA_TABLE.sql
@C:\Users\rodgl\DIR_ESCALATE_OPERATIONS_DATA_TABLE.sql
@C:\Users\rodgl\DIR_INSTANCE_ACTIONS_DATA_TABLE.sql
@C:\Users\rodgl\DIR_MIGRATE_OPERATIONS_DATA_TABLE.sql
@C:\Users\rodgl\DIR_NODE_ATTRIBUTES_DATA_TABLE.sql
@C:\Users\rodgl\DIR_QUIESCE_OPERATIONS_DATA_TABLE.sql
@C:\Users\rodgl\DIR_REASON_STRINGS_DATA_TABLE.sql
@C:\Users\rodgl\DIR_RESONATE_OPERATIONS_DATA_TABLE.sql
@C:\Users\rodgl\DIR_SERVICE_ATTRIBUTES_DATA_TABLE.sql
@C:\Users\rodgl\DIR_SERVICE_OPERATIONS_DATA_TABLE.sql
@C:\Users\rodgl\DIR_VICTIM_POLICY_DATA_TABLE.sql
@C:\Users\rodgl\DST_AFFECTED_TABLES_DATA_TABLE.sql
@C:\Users\rodgl\DST_ERROR_TABLE_DATA_TABLE.sql
@C:\Users\rodgl\DST_TRIGGER_TABLE_DATA_TABLE.sql
@C:\Users\rodgl\DUAL_DATA_TABLE.sql
@C:\Users\rodgl\DUC__DATA_TABLE.sql
@C:\Users\rodgl\ECOL__DATA_TABLE.sql
@C:\Users\rodgl\EDITION__DATA_TABLE.sql
@C:\Users\rodgl\EDITIONING_TYPES__DATA_TABLE.sql
@C:\Users\rodgl\EMPLOYEES_DATA_TABLE.sql
@C:\Users\rodgl\ENC__DATA_TABLE.sql
@C:\Users\rodgl\EPG__AUTH_DATA_TABLE.sql
@C:\Users\rodgl\ERROR__DATA_TABLE.sql
@C:\Users\rodgl\EV__DATA_TABLE.sql
@C:\Users\rodgl\EVCOL__DATA_TABLE.sql
@C:\Users\rodgl\EXPACT__DATA_TABLE.sql
@C:\Users\rodgl\EXPDEPACT__DATA_TABLE.sql
@C:\Users\rodgl\EXPDEPOBJ__DATA_TABLE.sql
@C:\Users\rodgl\EXP_HEAD__DATA_TABLE.sql
@C:\Users\rodgl\EXPIMP_TTS_CT__DATA_TABLE.sql
@C:\Users\rodgl\EXP_OBJ__DATA_TABLE.sql
@C:\Users\rodgl\EXPPKGACT__DATA_TABLE.sql
@C:\Users\rodgl\EXPPKGOBJ__DATA_TABLE.sql
@C:\Users\rodgl\EXP_SERVICE__DATA_TABLE.sql
@C:\Users\rodgl\EXP_STAT__DATA_TABLE.sql
@C:\Users\rodgl\EXTERNAL_LOCATION__DATA_TABLE.sql
@C:\Users\rodgl\EXTERNAL_SCN_ACTIVITY__DATA_TABLE.sql
@C:\Users\rodgl\EXTERNAL_TAB__DATA_TABLE.sql
@C:\Users\rodgl\FED_APPS_DATA_TABLE.sql
@C:\Users\rodgl\FED_APP_STATUS_DATA_TABLE.sql
@C:\Users\rodgl\FED_BINDS_DATA_TABLE.sql
@C:\Users\rodgl\FED_DEPENDENCY_DATA_TABLE.sql
@C:\Users\rodgl\FED_EDITIONS_DATA_TABLE.sql
@C:\Users\rodgl\FED_PATCHES_DATA_TABLE.sql
@C:\Users\rodgl\FED_STATEMENT_ERRORS_DATA_TABLE.sql
@C:\Users\rodgl\FED_VERSIONS_DATA_TABLE.sql
@C:\Users\rodgl\FET__DATA_TABLE.sql
@C:\Users\rodgl\FGA__DATA_TABLE.sql
@C:\Users\rodgl\FGACOL__DATA_TABLE.sql
@C:\Users\rodgl\FGA_LOG__DATA_TABLE.sql
@C:\Users\rodgl\FGA_LOG_FOR_EXPORT_TBL_DATA_TABLE.sql
@C:\Users\rodgl\FGR__FILE_GROUP_EXPORT_INFO_DATA_TABLE.sql
@C:\Users\rodgl\FGR__FILE_GROUP_FILES_DATA_TABLE.sql
@C:\Users\rodgl\FGR__FILE_GROUPS_DATA_TABLE.sql
@C:\Users\rodgl\FGR__FILE_GROUP_VERSIONS_DATA_TABLE.sql
@C:\Users\rodgl\FGR__TABLE_INFO_DATA_TABLE.sql
@C:\Users\rodgl\FGR__TABLESPACE_INFO_DATA_TABLE.sql
@C:\Users\rodgl\FILE__DATA_TABLE.sql
@C:\Users\rodgl\FINALHIST__DATA_TABLE.sql
@C:\Users\rodgl\FIXED_OBJ__DATA_TABLE.sql
@C:\Users\rodgl\GG__PACKAGE_MAPPING_DATA_TABLE.sql
@C:\Users\rodgl\GG__PROCEDURE_ANNOTATION_DATA_TABLE.sql
@C:\Users\rodgl\GG__PROC_OBJECT_EXCLUSION_DATA_TABLE.sql
@C:\Users\rodgl\GG__SUPPORTED_PACKAGES_DATA_TABLE.sql
@C:\Users\rodgl\GOLDENGATE__CONTAINER_RULES_DATA_TABLE.sql
@C:\Users\rodgl\GOLDENGATE__PRIVILEGES_DATA_TABLE.sql
@C:\Users\rodgl\HANG_MANAGER_PARAMETERS_DATA_TABLE.sql
@C:\Users\rodgl\HCS_ANALYTIC_VIEW__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_CLSFCTN__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_COL__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_DIM__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_HIER__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_KEY__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_LVL__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_LVLGRP__DATA_TABLE.sql
@C:\Users\rodgl\HCS_AV_MEAS__DATA_TABLE.sql
@C:\Users\rodgl\HCS_CLSFCTN__DATA_TABLE.sql
@C:\Users\rodgl\HCS_DIM__DATA_TABLE.sql
@C:\Users\rodgl\HCS_DIM_ATTR__DATA_TABLE.sql
@C:\Users\rodgl\HCS_DIM_DTM_ATTR__DATA_TABLE.sql
@C:\Users\rodgl\HCS_DIM_JOIN_PATH__DATA_TABLE.sql
@C:\Users\rodgl\HCS_DIM_LVL__DATA_TABLE.sql
@C:\Users\rodgl\HCS_DIM_LVL_KEY__DATA_TABLE.sql
@C:\Users\rodgl\HCS_DIM_LVL_KEY_ATTR__DATA_TABLE.sql
@C:\Users\rodgl\HCS_HIERARCHY__DATA_TABLE.sql
@C:\Users\rodgl\HCS_HIER_ATTR__DATA_TABLE.sql
@C:\Users\rodgl\HCS_HIER_COL__DATA_TABLE.sql
@C:\Users\rodgl\HCS_HIER_JOIN_PATH__DATA_TABLE.sql
@C:\Users\rodgl\HCS_HR_LVL__DATA_TABLE.sql
@C:\Users\rodgl\HCS_HR_LVL_ID__DATA_TABLE.sql
@C:\Users\rodgl\HCS_JOIN_COND_ELEM__DATA_TABLE.sql
@C:\Users\rodgl\HCS_LVLGRP_LVLS__DATA_TABLE.sql
@C:\Users\rodgl\HCS_LVL_ORD__DATA_TABLE.sql
@C:\Users\rodgl\HCS_MEASLST_MEASURES__DATA_TABLE.sql
@C:\Users\rodgl\HCS_SRC__DATA_TABLE.sql
@C:\Users\rodgl\HCS_SRC_COL__DATA_TABLE.sql
@C:\Users\rodgl\HEAT_MAP_EXTENT_STAT__DATA_TABLE.sql
@C:\Users\rodgl\HEAT_MAP_STAT__DATA_TABLE.sql
@C:\Users\rodgl\HIER__DATA_TABLE.sql
@C:\Users\rodgl\HIERLEVEL__DATA_TABLE.sql
@C:\Users\rodgl\HISTGRM__DATA_TABLE.sql
@C:\Users\rodgl\HIST_HEAD__DATA_TABLE.sql
@C:\Users\rodgl\HS__BASE_CAPS_DATA_TABLE.sql
@C:\Users\rodgl\HS__BASE_DD_DATA_TABLE.sql
@C:\Users\rodgl\HS_BULKLOAD_VIEW_OBJ_DATA_TABLE.sql
@C:\Users\rodgl\HS__CLASS_CAPS_DATA_TABLE.sql
@C:\Users\rodgl\HS__CLASS_DD_DATA_TABLE.sql
@C:\Users\rodgl\HS__CLASS_INIT_DATA_TABLE.sql
@C:\Users\rodgl\HS__FDS_CLASS_DATA_TABLE.sql
@C:\Users\rodgl\HS__FDS_CLASS_DATE_DATA_TABLE.sql
@C:\Users\rodgl\HS__FDS_INST_DATA_TABLE.sql
@C:\Users\rodgl\HS__INST_CAPS_DATA_TABLE.sql
@C:\Users\rodgl\HS__INST_DD_DATA_TABLE.sql
@C:\Users\rodgl\HS__INST_INIT_DATA_TABLE.sql
@C:\Users\rodgl\HS__PARALLEL_HISTOGRAM_DATA_DATA_TABLE.sql
@C:\Users\rodgl\HS__PARALLEL_METADATA_DATA_TABLE.sql
@C:\Users\rodgl\HS__PARALLEL_PARTITION_DATA_DATA_TABLE.sql
@C:\Users\rodgl\HS__PARALLEL_SAMPLE_DATA_DATA_TABLE.sql
@C:\Users\rodgl\ICOL__DATA_TABLE.sql
@C:\Users\rodgl\ICOLDEP__DATA_TABLE.sql
@C:\Users\rodgl\ID_GENS__DATA_TABLE.sql
@C:\Users\rodgl\IDL_CHAR__DATA_TABLE.sql
@C:\Users\rodgl\IDL_SB4__DATA_TABLE.sql
@C:\Users\rodgl\IDL_UB1__DATA_TABLE.sql
