REM INSERTING into SYS.HEAT_MAP_STAT$
SET DEFINE OFF;
Insert into SYS.HEAT_MAP_STAT$ (OBJ#,DATAOBJ#,TS#,TRACK_TIME,SEGMENT_ACCESS,FLAG,SPARE1,SPARE2,SPARE3,N_WRITE,N_FTS,N_LOOKUP) values ('-1','-1','-1',to_timestamp('04-02-2019','DD-MM-YYYY HH.MI.SSXFF AM'),'0','1',null,null,null,'0','0','0');
