REM INSERTING into SYS.HIERLEVEL$
SET DEFINE OFF;
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73648','1','1','3','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73648','1','2','2','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73648','1','3','1','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73649','1','1','2','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73649','1','2','4','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73649','1','3','1','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73649','1','4','3','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','1','1','2','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','1','2','3','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','1','3','1','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','1','4','5','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','2','1','2','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','2','2','7','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','2','3','8','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','2','4','6','0',null,null,null,null);
Insert into SYS.HIERLEVEL$ (DIMOBJ#,HIERID#,POS#,LEVELID#,JOINKEYID#,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','2','5','4','0',null,null,null,null);
