REM INSERTING into SYS.HIER$
SET DEFINE OFF;
Insert into SYS.HIER$ (DIMOBJ#,HIERID#,HIERNAME,SPARE1,SPARE2,SPARE3,SPARE4) values ('73648','1','CHANNEL_ROLLUP',null,null,null,null);
Insert into SYS.HIER$ (DIMOBJ#,HIERID#,HIERNAME,SPARE1,SPARE2,SPARE3,SPARE4) values ('73649','1','PROMO_ROLLUP',null,null,null,null);
Insert into SYS.HIER$ (DIMOBJ#,HIERID#,HIERNAME,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','1','CAL_ROLLUP',null,null,null,null);
Insert into SYS.HIER$ (DIMOBJ#,HIERID#,HIERNAME,SPARE1,SPARE2,SPARE3,SPARE4) values ('73650','2','FIS_ROLLUP',null,null,null,null);
